name: Deploy Backend to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # --- CORRECCIÓN: El parámetro se llama 'region' ---
          region: ${{ secrets.AWS_REGION }}
          # --------------------------------------------------
          application_name: portfolio-backend
          environment_name: portfolio-backend-prod
          version_label: "v${{ github.run_number }}-${{ github.sha }}" # Versión más única
          deployment_package: backend/target/backend-0.0.1-SNAPSHOT.jar